# GoReleaser configuration for grub - provider-agnostic CRUD for Go

version: 2

project_name: grub

dist: .dist

builds:
  # Skip building binaries for the main library since it's a library package
  - skip: true

archives:
  - id: source
    files:
      - "*.go"
      - "go.mod"
      - "go.sum"
      - "LICENSE"
      - "README.md"
      - "Makefile"
      - ".golangci.yml"
      - "pkg/**/go.mod"
      - "pkg/**/go.sum"
      - "pkg/**/*.go"
      - "testing/**/go.mod"
      - "testing/**/go.sum"
      - "testing/**/*.go"
    name_template: "{{ .ProjectName }}_{{ .Version }}_source"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Documentation"
      regexp: '^.*?docs?(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "Testing"
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: "Maintenance"
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 6
    - title: "Other Changes"
      order: 999
  filters:
    exclude:
      - "^Merge"
      - "^merge"
      - "^wip"
      - "^WIP"
      - "^docs:"
      - "^docs\\("
      - "^test:"
      - "^test\\("

release:
  github:
    owner: zoobzio
    name: grub

  name_template: "{{ .ProjectName }} v{{ .Version }}"
  draft: false
  prerelease: auto
  mode: append

  header: |
    ## grub v{{ .Version }}

    Provider-agnostic CRUD for Go.

    ### Installation

    ```bash
    go get github.com/zoobzio/grub@v{{ .Version }}
    ```

    ### Requirements
    - Go 1.23 or higher (toolchain 1.25 recommended)

  footer: |
    ---

    **Full Documentation:** https://github.com/zoobzio/grub/tree/v{{ .Version }}

    Thanks to all contributors!

announce:
  skip: true

snapshot:
  version_template: "{{ .Tag }}-next"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

git:
  tag_sort: -version:refname
  ignore_tags:
    - ".*-rc.*"
    - ".*-beta.*"
    - ".*-alpha.*"
